#!/bin/bash

make "do_fits" || exit 1

n_threads="8"

#----------------------------------------------------------------------------------------------------

function ProcessOne()
{
	local buffer="$1"

	for d in $buffer
	do
		#echo "    $d"
		./do_fits "$d" &> "$d/do_fits.log"

        res="$?"

        if [ $res -eq 0 ]
        then
            continue
        fi

        case $res in
            1)
			  echo "WARNING: some plots missing in $d"
              ;;
            *)
			  echo "ERROR: run problem in $d"
              ;;
        esac
	done
}

#----------------------------------------------------------------------------------------------------

echo "* building directory list"

# collect data
idx=0
input=()
while [ -n "$1" ]
do
	echo "    - $1"

	for dir in `find $1 -type d`
	do
		if [ -f "$dir/output.root" ]
		then
			input[$idx]="${input[$idx]} $dir"
			idx=$(( (idx+1) % n_threads ))
		#else
			#echo "ERROR: no output.root in $dir"
		fi
	done

	shift
done

echo "* running fits"

# run in parallel
for (( idx=0; idx<n_threads; idx++))
do
	ProcessOne "${input[$idx]}" &
done

wait

echo "* done"
