#!/bin/bash

function SubmitOneDir()
{
	local buf="$tag"

	fill=${buf#fill}
	fill=${fill%%_*}

	buf=${buf#*_}
	xangle=${buf%%_*}
	xangle=${xangle#xangle}

	buf=${buf#*_}
	beta=${buf%%_*}
	beta=${beta#beta}

	echo "* $fill, $xangle, $beta"

	# get input
	input="process.source.fileNames.append(\"root://eoscms.cern.ch/${input_dir}/${tag}\")"

	# make work directory
	subdir="fill_$fill/xangle_${xangle}_beta_${beta}_stream_${stream}"
	dir="$top_dir/$subdir"
	mkdir -p "$dir"

	# clean work directory
	rm -rf "$dir/submitted"
	rm -rf "$dir/finished"
	rm -rf "$dir/success"
	rm -rf "$dir/output.root"
	rm -rf "$dir/output_validation.root"
	rm -rf "$dir/output_tracks.root"
	rm -rf "$dir/output_optics.root"
	rm -rf "$dir/log"

	full_dir="`pwd -P`/$dir"

	# make config
	cat "template_cfg.py" | sed -e "\
			s|\$input|$input|g;\
			s|\$year|$year|g;\
			s|\$fill|$fill|g;\
			s|\$xangle|$xangle|g;\
			s|\$beta|$beta|g;\
			s|\$output|output.root|g;\
		" > "$dir/cfg.py"

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.untracked.vstring("

		search="fill${fill}_xangle${xangle}_beta${beta}"
		for f_in in `eos ls "$input_dir"|grep ".root"|grep "$search"`
		do
			echo "    \"root://eostotem.cern.ch/${input_dir}/${f_in}\","
		done

		echo ")"
	) > "$dir/input_files.py"

	# make job
	cat "template_job" | sed "\
			s|\$sw_dir|$sw_dir|g;\
			s|\$job_dir|$full_dir|g;\
		" > "$dir/job"
	chmod u+x "$dir/job"

	# add submission line
	(
		echo ""
		echo "dir=$subdir"
		echo "queue"
	) >> "$condor_file_sub"

	# local run
	# TODO
	#cd "$dir"
	#cmsRun "cfg.py" &
	#cd - &> /dev/null
}

#----------------------------------------------------------------------------------------------------

function Submit()
{
	top_dir="data/$year/$version"

	mkdir -p "$top_dir"

	condor_file_sub="$top_dir/condor.sub"

	# initiate submission script
	(
		local base_dir_full="$(pwd)/$top_dir"
		echo "executable = $base_dir_full/\$(dir)/job"
		echo "arguments = \$(ClusterId) \$(ProcId) \\\"\$(dir)\\\""
		echo "output = $base_dir_full/\$(dir)/out"
		echo "error = $base_dir_full/\$(dir)/err"
		echo "log = $base_dir_full/condor_${selection}.log"

		echo "+MaxRuntime = 10800"
		#echo "+JobBatchName = \"$job_name\""
		#echo "requirements = (OpSysAndVer =?= \"SLCern6\")"
		echo "requirements = (OpSysAndVer =?= \"CentOS7\")"

	) > "$condor_file_sub"

	# loop over input files
	for tag in `eos ls "$input_dir"|grep .root|sed "s/_[a-zA-Z]*\.root//"|sort|uniq`
	do
		SubmitOneDir
	done

	# submit
	echo "In order to submit do:"
	echo "    condor_submit \"$condor_file_sub"\"
	#condor_submit "$condor_file_sub"
}

#----------------------------------------------------------------------------------------------------

year="2016"
#stream="SingleMuon"
#stream="ZeroBias"
stream="ALL"

#version="version1"
#input_dir="/eos/totem/data/ctpps/reconstruction/2016/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step3/CMSSW_10_6_X_2019-05-03-1100/src" # at f0d588ede3ddbb633630286b5bea6ab28cf5afda (synchronised with step2 branch)
#Submit

#version="version2"
#input_dir="/eos/totem/data/ctpps/reconstruction/2016/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at 912a9030069abd4e0b686e45d6230c46b1468581
# with GT 106X_dataRun2_testPPS_v1
#Submit

#version="version3"
#input_dir="/eos/totem/data/ctpps/reconstruction/2016/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at e516024b2c8680810c37c7513138acae1a032d51 (Added optics plotter module)
# with GT 106X_dataRun2_testPPS_v1, local alignment
#Submit

#version="version4"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at 83be64d0c9566ba3aaa14142204984b9ffe1b57f (Use version1 of 2016 post-TS2 optics)
# with GT 106X_dataRun2_v11, local alignment
#Submit

#version="version5"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at f2e490a377efd0fc22deee052cfbb8683747a039 (Switched to version2 of 2016 pre-TS2 optics)
# with GT 106X_dataRun2_v11, local alignment
#Submit

version="version6"
input_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/physics_runs/rec-hit-version1"
sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at e5ae42006066be39938358106d921031eac4c0a4
# with GT 106X_dataRun2_v26, alignment local, optics local
Submit

#----------------------------------------------------------------------------------------------------

year="2017"
#stream="DoubleEG"
stream="ALL"

#version="version1"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at 0f7f0ddb8ca264f513f7a5d32e42f9202a9b3e3d
#Submit

#version="version1-fix"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at fc3ad052213d1077e5c7e3abfdac904e2fd09a1e, with alignment alignment_export_2019_03_18.5.xml
#Submit

#version="version2"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at fbd63215d928924b691c953f58afd4791f8fac06
#Submit

#version="version3"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at fc3ad052213d1077e5c7e3abfdac904e2fd09a1e
#Submit

#version="version4"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at 1198954cacd8dbad8df546dcfb658847f6321e70 (2017+2018 optics version 3)
#Submit

#version="version5"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at 4a9108a21ba75f2a98807360ddc0173e9da143d9 (updated 2017 alignment of tracking RPs)
#Submit

#version="version6"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at c393ef4902c9ccb8012f673d855e749ec4a2c494 (new timing-RP alignment for 2017)
#Submit

#version="version7"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at d0ec5aa0d2b4c763188c4f3f37b28cb1ef35dbbb (all single-RP output saved)
#Submit

#version="version8"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step3/CMSSW_10_6_X_2019-05-03-1100/src" # at f0d588ede3ddbb633630286b5bea6ab28cf5afda (synchronised with step2 branch)
#Submit

#version="version9"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at 912a9030069abd4e0b686e45d6230c46b1468581
# with GT 106X_dataRun2_testPPS_v1
#Submit

#version="version10"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at e516024b2c8680810c37c7513138acae1a032d51 (Added optics plotter module)
# with GT 106X_dataRun2_testPPS_v1, local alignment
#Submit

#version="version11"
#input_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at a3801a1be193158a372202ef2cb1cb728644bc25 (Added new alignment candidate)
# with GT 106X_dataRun2_testPPS_v1, local alignment (2019_06_12), local optics (2017 --> version4)
#Submit

#version="version12"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2017/physics_runs/rec-hit-version2"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at 1ebb05f3c961cde76c7386effb43b4de5a0ee5b3
# with GT 106X_dataRun2_v24, alignment local, optics local
#Submit

version="version13"
input_dir="/eos/cms/store/group/phys_pps/reconstruction/2017/physics_runs/rec-hit-version2"
sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at e5ae42006066be39938358106d921031eac4c0a4
# with GT 106X_dataRun2_v26, alignment local, optics local
Submit

#----------------------------------------------------------------------------------------------------

year="2018"
#stream="SingleMuon"
stream="ALL"

#version="version1"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step2/CMSSW_10_6_0_pre2/src" # at d0ec5aa0d2b4c763188c4f3f37b28cb1ef35dbbb (all single-RP output saved)
#Submit

#version="version2"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step3/CMSSW_10_6_X_2019-05-03-1100/src" # at f0d588ede3ddbb633630286b5bea6ab28cf5afda (synchronised with step2 branch)
#Submit

#version="version3"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step3/CMSSW_10_6_X_2019-05-03-1100/src"
# at 41de0d02511195da4c52cdfe2b3ae7e41b2c4494 (with local alignment), with GT 106X_dataRun2_v10, optics PPSOpticalFunctions_offline_v2
#Submit

#version="version4"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at 912a9030069abd4e0b686e45d6230c46b1468581
# with GT 106X_dataRun2_testPPS_v1
#Submit

#version="version5"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at e516024b2c8680810c37c7513138acae1a032d51 (Added optics plotter module)
# with GT 106X_dataRun2_testPPS_v1, local alignment
#Submit

#version="version6"
#input_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/software/ctpps/development/proton_reco_step4/CMSSW_10_6_0/src"
# at 94f620beb3c1adf67af9155338a61e783441e2c4 (Added xi histograms for different track multiplicities)
# with GT 106X_dataRun2_testPPS_v1, local alignment
#Submit

#version="version7"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at cf4932b701f44a26a3a45a219925bb5d7fd93ed0 (ctppsAlignment_cff included by default)
# with GT 106X_dataRun2_v11, alignment local, optics local
#Submit

#version="version8"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at ???
# with GT 106X_dataRun2_v11, alignment local, optics local
#Submit

#version="version9"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at 0b855eef4cc (2018 alignment updated)
# with GT 106X_dataRun2_v11, alignment local, optics local
#Submit

#version="version10"
#input_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/rec-hit-version1"
#sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at 58c6c727517d325d4efbe3a88fdadedbc3a44a4d
# with GT 106X_dataRun2_v24, alignment local, optics local
#Submit

version="version11"
input_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/rec-hit-version1"
sw_dir="/afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src"
# at e5ae42006066be39938358106d921031eac4c0a4
# with GT 106X_dataRun2_v26, alignment local, optics local
Submit
