#!/bin/bash

for year in 2016 2017 2018
do
	rm -rf "$year"

	mkdir "$year"
	ln -s "../settings_$year.asy" "$year/settings.asy"

	for dir in "apertures" "hit_distributions" "quality" "th_x" "th_y" "vtx_y" "xi"
	do
		mkdir "$year/$dir"

		for file in templates/$dir/*.asy
		do
			file=${file##*/}
			ln -s "../../templates/$dir/$file" "$year/$dir/$file"
		done
	done
done
